version: "3.9"

services:
  web:
    build: .
    container_name: movie_check
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - movienet

  nginx:
    image: nginx:alpine
    container_name: moviestream_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - movienet

networks:
  movienet:
    driver: bridge
